import React,{useState}from"react";
const menu=[["menu-01.jpg","대표 메뉴","고기별국수","맑고 깔끔한 육수에 고기와 지단을 올린 별국수 대표 메뉴"],["menu-02.jpg","대표 메뉴","비빔고기별국수","매콤달콤한 양념과 고기 토핑을 함께 즐기는 인기 메뉴"],["menu-03.jpg","국수 메뉴","별소면","다양한 상권과 고객층에 대응할 수 있는 기본 국수 메뉴"],["menu-04.jpg","분식 & 사이드","분식 & 사이드","떡볶이·어묵·김밥·만두·튀김 등을 상권에 맞춰 구성"]];
const models=[["01","주거·생활상권","12~18평","잔치·비빔·어묵국수, 돈가스·덮밥"],["02","오피스·역세권","10~16평","별국수, 비빔국수, 짜장, 국밥·덮밥"],["03","학교·학원가","8~15평","떡볶이, 어묵, 튀김, 닭강정, 간편국수"],["04","대형마트","12~20평","국수, 떡볶이, 돈가스, 덮밥, 가족세트"],["05","푸드코트","6~12평","베스트 국수 3~4종, 덮밥 2종, 사이드"],["06","관광지·해외","12~25평","K-누들, 비빔면, 떡볶이, 닭강정"]];
const costs=[["가맹비","500만원"],["교육비","300만원"],["계약이행보증금","300만원"],["주방 설비비","1,500만원부터"],["인테리어비","평당 180만원부터"],["설계·기본감리","선택 150만원"],["로열티","VAT 제외 매출의 2%"]];
export default function ByeolGuksu({consultationEndpoint=""}){const[open,setOpen]=useState(false),[sent,setSent]=useState(false),[sending,setSending]=useState(false);const to=id=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setOpen(false)};async function submit(e){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries());if(!d.name||!d.phone||!d.region)return alert("이름, 연락처, 희망 지역을 입력해주세요.");setSending(true);try{if(consultationEndpoint)await fetch(consultationEndpoint,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({payload:JSON.stringify({type:"BYEOLGUKSU",submittedAt:new Date().toISOString(),...d})})});else localStorage.setItem("byeolguksu_last_inquiry",JSON.stringify(d));f.reset();setSent(true)}catch(e){alert("상담 신청 중 오류가 발생했습니다.")}finally{setSending(false)}}return <div className="byeol"><header className="byeoltop"><a href="/" className="byeolbrand"><b>★</b><span>별국수<small>K-NOODLE FRANCHISE</small></span></a><button className="hamb" onClick={()=>setOpen(!open)}>☰</button><nav className={open?"open":""}>{[["about","브랜드"],["menu","메뉴"],["model","창업모델"],["cost","창업비용"],["support","창업지원"],["process","창업절차"],["contact","가맹문의"]].map(x=><a key={x[0]} href={"#b-"+x[0]} onClick={e=>{e.preventDefault();to("b-"+x[0])}}>{x[1]}</a>)}</nav></header>
<section className="bhero"><div><p className="eyebrow">K-NOODLE FRANCHISE · 2026</p><h1>상권에 맞추고,<br/><em>매장에 맞춰 성장합니다.</em></h1><p>한 그릇의 국수에서 시작해 밥류·간식류·돈가스 등을 선택적으로 결합합니다. 점포 크기와 고객에 맞는 현실적인 메뉴와 운영방식을 함께 설계합니다.</p><button className="red" onClick={()=>to("b-contact")}>내 상권 상담받기 ↗</button></div><div className="bvisual"><strong>★<br/>BYEOL<br/>GUKSU</strong><small>NOODLE & K-FOOD</small></div></section>
<section id="b-about" className="bsec"><p className="eyebrow">BRAND</p><h2>하나의 매장을<br/>하나의 방식으로 제한하지 않습니다.</h2><p>모든 가맹점이 전 메뉴를 의무적으로 운영하지 않습니다. 상권·주방면적·조리인력·판매자료를 분석해 핵심과 선택 메뉴를 구성합니다.</p><div className="b3">{["상권 맞춤형 운영","효율적인 메뉴 구성","함께 성장하는 브랜드"].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{["지역과 고객층에 맞춰 메뉴와 운영방식을 설계합니다.","국수를 중심으로 밥·분식·돈가스 등을 선택적으로 결합합니다.","본사와 가맹점이 함께 고민하고 지속적으로 발전합니다."][i]}</p></article>)}</div></section>
<section id="brands" className="bdark"><p className="eyebrow">BYEOL BRAND PORTFOLIO</p><h2>상권과 고객에 맞는<br/>별 브랜드를 선택하세요.</h2><div className="b3"><article><b>01</b><h3>별국수</h3><p>국수 중심에 밥·분식·돈가스를 선택적으로 더하는 기본형.</p></article><article><b>02</b><h3>별스트리트</h3><p>국수에 떡볶이·닭강정·어묵·김밥·튀김 등을 더한 복합형.</p></article><article><b>03</b><h3>별그릴</h3><p>한국식 BBQ와 식사·모임에 적합한 그릴형 모델.</p></article></div></section>
<section id="b-menu" className="bsec cream"><p className="eyebrow">MENU SYSTEM</p><h2>대표 메뉴부터<br/>상권 선택 메뉴까지</h2><p>메뉴 추가·변경은 본사 사전협의 후 원가·조리시간·품질·공급 가능성을 검토해 적용합니다.</p><div className="menugrid">{menu.map(m=><article key={m[2]}><img src={"/images/byeolguksu/"+m[0]} alt={m[2]}/><small>{m[1]}</small><h3>{m[2]}</h3><p>{m[3]}</p></article>)}</div></section>
<section id="b-model" className="bsec"><p className="eyebrow">STORE MODEL</p><h2>상권이 다르면<br/>잘 팔리는 메뉴도 다릅니다.</h2><div className="modelgrid">{models.map(m=><article key={m[0]}><b>{m[0]}</b><h3>{m[1]}</h3><strong>{m[2]}</strong><p>{m[3]}</p></article>)}</div></section>
<section id="b-cost" className="bsec cream"><p className="eyebrow">INVESTMENT</p><h2>15평 표준점<br/>기본 창업비용</h2><div className="cost">{costs.map(c=><div key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong></div>)}</div><div className="summary"><strong>기본 합계 5,450만원부터</strong><p>VAT 및 별도항목 제외. 간판·의탁자·POS·키오스크·주방기물·초도물품 포함 시 약 7,000만~8,300만원 예상. 점포 보증금·권리금·철거·냉난방·덕트·전기증설·소방·몰 지정공사 등은 별도입니다.</p></div></section>
<section id="b-support" className="bsec"><p className="eyebrow">STARTUP & OPERATION SUPPORT</p><h2>입지 검토부터<br/>운영 안정화까지</h2><div className="b3">{["스마트 점포관리","스마트 호출 시스템","디지털 레시피","물류·신용거래","SNS 공동 마케팅","창업지원 컨설팅"].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{["매출·발주·재고·공지·점검을 한 화면에서.","NFC와 스마트TV로 주문·픽업 안내.","사진·영상·계량기준과 신메뉴 업데이트.","배송권역과 기준에 맞춘 안정적인 공급.","숏폼·오픈홍보·지역광고 콘텐츠 지원.","정책자금·보증·교육·지원사업 진단."][i]}</p></article>)}</div></section>
<section id="b-process" className="bdark"><p className="eyebrow">OPENING PROCESS</p><h2>상담부터 정식 오픈까지</h2><div className="process">{["상담신청","상권·점포검토","모델·메뉴제안","정보제공·계약","설계·시공","교육·오픈"].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{["희망지역·투자규모·운영계획 확인","경쟁환경·시설조건·수익성 검토","권장면적·메뉴·투자범위 제시","법정서류 제공과 숙고기간 준수","도면·동선·설비·사인 확정","조리·서비스·위생 교육과 현장지원"][i]}</p></article>)}</div></section>
<section id="b-contact" className="bcontact"><div><p className="eyebrow">FRANCHISE INQUIRY</p><h2>상권에 맞는<br/>별 브랜드를 함께 설계해보세요.</h2><p>관심 브랜드와 희망 지역, 투자 범위를 알려주시면 검토해드립니다.</p><strong>matchon7@daum.net</strong></div><form onSubmit={submit}><label>관심 브랜드<select name="brand"><option>별국수</option><option>별스트리트</option><option>별그릴</option></select></label><label>성명 / 업체명 *<input name="name" required/></label><label>연락처 *<input name="phone" required/></label><label>희망 출점지역 *<input name="region" required/></label><label>투자 가능범위<select name="budget"><option>5,000만원 이하</option><option>5,000~7,000만원</option><option>7,000~1억원</option><option>1억원 이상</option><option>상담 필요</option></select></label><label>문의내용<textarea name="message" rows="5"/></label><label className="check"><input type="checkbox" required/> 가맹상담을 위한 개인정보 수집·이용에 동의합니다.</label><button className="red" disabled={sending}>{sending?"접수 중...":"가맹상담 신청하기"}</button>{sent&&<p className="ok">상담 신청이 접수되었습니다.</p>}</form></section>
<footer><b>별국수</b><span>K-NOODLE FRANCHISE · 상담 matchon7@daum.net</span><p>© 2026 MATCHON. All Rights Reserved.</p></footer></div>}